name: Deploy to Amazon ECS

on:
  push:
    branches: [ "development" ]

env:
  AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: medicine           # set this to your Amazon ECR repository name
  ECS_SERVICE: medicine                 # set this to your Amazon ECS service name
  ECS_CLUSTER: medicine                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: medicine           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

